def make_mut(sequences,wt):
	top_r = []
	for s in sequences:
		i = 1
		top = ''
		while i <= len(wt):
			if wt[i-1] != s[i-1]:
				if len(top)>0:
					top += ','
				top += wt[i-1]+'A'+str(i)+s[i-1]+','+wt[i-1]+'B'+str(i)+s[i-1]
			i+=1
		top += ';'
		top_r.append(top)
	return top_r


with open('MDH_sequences_aligned.fasta','r') as fin:
	ll = fin.readlines()

sequences = []
seq_name = []
for l in ll:
	if l[0] != '>':
		sequences.append(l.strip('\n'))
	else:
		seq_name.append(l)



Anc_T6 = ['Anc13','Anc10','Anc7','Anc5','Anc3','Anc6']
Anc_T9 = ['Anc13']

Anc_T6 = ['MDH.T6.asr.0.axes.'+x for x in Anc_T6]
Anc_T9 = ['MDH.T9.asr.0.axes.'+x for x in Anc_T9]
Anc = Anc_T6 + Anc_T9
with open('ML_seq.fa','r') as fin:
	ll = fin.readlines()
n = 0
for l in ll:
	if n == 1:
		sequences.append(l.strip('\n'))
		n = 0
	elif l.strip()[1:] in Anc:
		n = 1
		seq_name.append(l)
	else:
		n = 0

# wt_T6 = 'MGEPLRVCVTGAAGQIAYSLLYSVAKGDVFGPNQRISLVLLDIESMMGVLEGIVMELVDCALPLLAEIKPTANVSEAFKDISVAILVGAMPRREGMERKDLLKANVRIFKAQGQALDQFAKKDVKVIVVGNPANTNAFICKKYAPSIPAKNFTCLTRLDHNRAMAQIAIRVGVSAQDVKNVIIWGNHSSTQFPDVRHALVTINGKDVPVTEAVKDDHWLKTEFISTVQKRGAAVIAARKLSSAMSAAKAICDHLRSWWFGTPPNQWVSMGVCSDGSYGTEPGLIYSFPVEIANGDWKIVQGLNVDDFSREKMNLTMKELQEERNSALESCED'
wt_T9 = 'MGEPLRVCVTGAAGQIAYSLLYSVAKGDVFGPNQRISLVLLDIESMMGVLEGIVMELVDCALPLLADIKPTANVNEAFKDISVAILVGAMPRREGMERKDLLKANVRIFKAQGQALDQFAKKDVKVIVVGNPANTNAFICKKYAPSIPAKNFTCLTRLDHNRAMAQIAIRVGVSAQDVKNVIIWGNHSSTQFPDVRHAVVNINGKDVPVTEAVKDDHWLKTDFISTVQKRGAAVIAARKLSSAMSAAKAICDHLRSWWFGTPPNQWVSMGVCSDGSYGTEPGLIYSFPVEIANGDWKIVQGLNVDDFSREKMNLTQKELQEERNSALESCED'
# wt_Anc10 = 'MGEPLRVCVTGAAGQIAYSLLYSVAKGDVFGPNQRISLVLLDIESMMGVLEGIVMELVDCALPLLAEIKPTANVSEAFKDISVAILVGAMPRREGMERKDLLKANVRIFKAQGQALDQFAKKDVKVIVVGNPANTNAFICKKYAPSIPAKNFTCLTRLDHNRAMAQIAIRVGVSAQDVKNVIIWGNHSSTQFPDVRHALVTINGKDVPVTEAVKDDHWLKTDFISTVQKRGAAVIAARKLSSAMSAAKAICDHLRSWWFGTPPNQWVSMGVCSDGSYGTEPGLIYSFPVEIANGDWKIVQGLNVDDFSREKMNLTQKELQEERNSALESCED'

top_r = make_mut(sequences,wt_T9)

for i,j in zip(seq_name,top_r):
	print(i.strip())
	print(j)